services:
  cloudsecure-webmail:
    image: ghcr.io/morgankryze/cloudsecure-webmail:latest
    container_name: cloudsecure-webmail
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 80
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true
    depends_on:
      - cloudsecure-backend

  cloudsecure-backend:
    image: ghcr.io/morgankryze/cloudsecure-backend:latest
    container_name: cloudsecure-backend
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 9000
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true

  cloudsecure-webfake:
    image: ghcr.io/morgankryze/cloudsecure-webfake:latest
    container_name: cloudsecure-webfake
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 80
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true

  cloudsecure-webtimeout:
    image: ghcr.io/morgankryze/cloudsecure-webtimeout:latest
    container_name: cloudsecure-webtimeout
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    expose:
      - 80
    networks:
      - pangolin
    labels:
      com.centurylinklabs.watchtower.enable: true

networks:
  pangolin:
    external: true