name: Build and Push Docker Images

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.api
          push: true
          tags: |
            ghcr.io/morgankryze/cloudsecure-backend:latest
            ghcr.io/morgankryze/cloudsecure-backend:${{ github.sha }}
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Build and push Webmail Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.webmail
          push: true
          tags: |
            ghcr.io/morgankryze/cloudsecure-webmail:latest
            ghcr.io/morgankryze/cloudsecure-webmail:${{ github.sha }}
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Build and push Webfake Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/Dockerfile.webfake
          push: true
          tags: |
            ghcr.io/morgankryze/cloudsecure-webfake:latest
            ghcr.io/morgankryze/cloudsecure-webfake:${{ github.sha }}
          build-args: |
            VERSION=${{ github.ref_name }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
